APPCMD add apppool /name:AdministrativeBuilding
APPCMD add apppool /name:AdministrativeBuildingAPI
APPCMD add apppool /name:AlAzharyBuilding
APPCMD add apppool /name:AlAzharyBuildingAPI
APPCMD add apppool /name:Educationalbuildings
APPCMD add apppool /name:EducationalbuildingsAPI
APPCMD add apppool /name:EducationalStudy
APPCMD add apppool /name:EducationalStudyAPI
APPCMD add apppool /name:FilesApi
APPCMD add apppool /name:Gateway
APPCMD add apppool /name:HC
APPCMD add apppool /name:HealthyUnit
APPCMD add apppool /name:HealthyUnitAPI
APPCMD add apppool /name:Land
APPCMD add apppool /name:LandAPI
APPCMD add apppool /name:linkAuthorityMinistryPro
APPCMD add apppool /name:linkAuthorityMinistryProAPI
APPCMD add apppool /name:LookUpProject
APPCMD add apppool /name:NurseriesKindergartenProgram
APPCMD add apppool /name:NurseriesKindergartenProgramAPI
APPCMD add apppool /name:PostOffice
APPCMD add apppool /name:PostOfficeAPI
APPCMD add apppool /name:YouthCenter
APPCMD add apppool /name:YouthCenterAPI

