dotnet sln TotalAPI.sln add Accounts/Accounts.csproj
dotnet sln TotalAPI.sln add AccountsAPI/AccountsAPI.csproj
dotnet sln TotalAPI.sln add Assay/Assay.csproj
dotnet sln TotalAPI.sln add AssayAPI/AssayAPI.csproj
dotnet sln TotalAPI.sln add AssayAssayListAuthoritypricelist/AssayAssayListAuthoritypricelist.csproj
dotnet sln TotalAPI.sln add AssayAssayListAuthoritypricelistAPI/AssayAssayListAuthoritypricelistAPI.csproj
dotnet sln TotalAPI.sln add AssayAssayListBuildingAssay/AssayAssayListBuildingAssay.csproj
dotnet sln TotalAPI.sln add AssayAssayListBuildingAssayAPI/AssayAssayListBuildingAssayAPI.csproj
dotnet sln TotalAPI.sln add AssayAssayListBuildingmodelswork/AssayAssayListBuildingmodelswork.csproj
dotnet sln TotalAPI.sln add AssayAssayListBuildingmodelsworkAPI/AssayAssayListBuildingmodelsworkAPI.csproj
dotnet sln TotalAPI.sln add AssayBuildingWeightFactorList/AssayBuildingWeightFactorList.csproj
dotnet sln TotalAPI.sln add AssayBuildingWeightFactorListAPI/AssayBuildingWeightFactorListAPI.csproj
dotnet sln TotalAPI.sln add AssayListofcreationofworksofothers/AssayListofcreationofworksofothers.csproj
dotnet sln TotalAPI.sln add AssayListofcreationofworksofothersAPI/AssayListofcreationofworksofothersAPI.csproj
dotnet sln TotalAPI.sln add AssayListStandardizationCode/AssayListStandardizationCode.csproj
dotnet sln TotalAPI.sln add AssayListStandardizationCodeAPI/AssayListStandardizationCodeAPI.csproj
dotnet sln TotalAPI.sln add AssayListSubsystemCode/AssayListSubsystemCode.csproj
dotnet sln TotalAPI.sln add AssayListSubsystemCodeAPI/AssayListSubsystemCodeAPI.csproj
dotnet sln TotalAPI.sln add AssayPostOfficeDevelopment/AssayPostOfficeDevelopment.csproj
dotnet sln TotalAPI.sln add AssayPostOfficeDevelopmentAPI/AssayPostOfficeDevelopmentAPI.csproj
dotnet sln TotalAPI.sln add AssaySubsystemOfAssays/AssaySubsystemOfAssays.csproj
dotnet sln TotalAPI.sln add AssaySubsystemOfAssaysAPI/AssaySubsystemOfAssaysAPI.csproj
dotnet sln TotalAPI.sln add Assayunctionsofitemsandelementsoftheproject/Assayunctionsofitemsandelementsoftheproject.csproj
dotnet sln TotalAPI.sln add AssayunctionsofitemsandelementsoftheprojectAPI/AssayunctionsofitemsandelementsoftheprojectAPI.csproj
dotnet sln TotalAPI.sln add AssayWorkofcloudsassays/AssayWorkofcloudsassays.csproj
dotnet sln TotalAPI.sln add AssayWorkofcloudsassaysAPI/AssayWorkofcloudsassaysAPI.csproj
dotnet sln TotalAPI.sln add BalancingPart6/BalancingPart6.csproj
dotnet sln TotalAPI.sln add BalancingPart6API/BalancingPart6API.csproj
dotnet sln TotalAPI.sln add BranchManager/BranchManager.csproj
dotnet sln TotalAPI.sln add BranchManagerAPI/BranchManagerAPI.csproj
dotnet sln TotalAPI.sln add Buildinginspectionandvaliditycertificate/Buildinginspectionandvaliditycertificate.csproj
dotnet sln TotalAPI.sln add BuildinginspectionandvaliditycertificateAPI/BuildinginspectionandvaliditycertificateAPI.csproj
dotnet sln TotalAPI.sln add Businesstoothers/Businesstoothers.csproj
dotnet sln TotalAPI.sln add BusinesstoothersAPI/BusinesstoothersAPI.csproj
dotnet sln TotalAPI.sln add Case/Case.csproj
dotnet sln TotalAPI.sln add CaseAPI/CaseAPI.csproj
dotnet sln TotalAPI.sln add Clinic/Clinic.csproj
dotnet sln TotalAPI.sln add ClinicAPI/ClinicAPI.csproj
dotnet sln TotalAPI.sln add ComputerMaintenance/ComputerMaintenance.csproj
dotnet sln TotalAPI.sln add ComputerMaintenanceAPI/ComputerMaintenanceAPI.csproj
dotnet sln TotalAPI.sln add CooperativeSociety/CooperativeSociety.csproj
dotnet sln TotalAPI.sln add CooperativeSocietyAPI/CooperativeSocietyAPI.csproj
dotnet sln TotalAPI.sln add EducationalStudy/EducationalStudy.csproj
dotnet sln TotalAPI.sln add EducationalStudyAPI/EducationalStudyAPI.csproj
dotnet sln TotalAPI.sln add Employee/Employee.csproj
dotnet sln TotalAPI.sln add EmployeeAPI/EmployeeAPI.csproj
dotnet sln TotalAPI.sln add Expropriation/Expropriation.csproj
dotnet sln TotalAPI.sln add ExpropriationAPI/ExpropriationAPI.csproj
dotnet sln TotalAPI.sln add Extract/Extract.csproj
dotnet sln TotalAPI.sln add ExtractAPI/ExtractAPI.csproj
dotnet sln TotalAPI.sln add Followupproject/Followupproject.csproj
dotnet sln TotalAPI.sln add FollowupprojectAPI/FollowupprojectAPI.csproj
dotnet sln TotalAPI.sln add Guild/Guild.csproj
dotnet sln TotalAPI.sln add GuildAPI/GuildAPI.csproj
dotnet sln TotalAPI.sln add HealthUnitsMinistry/HealthUnitsMinistry.csproj
dotnet sln TotalAPI.sln add HealthUnitsMinistryAPI/HealthUnitsMinistryAPI.csproj
dotnet sln TotalAPI.sln add Internationalcooperation/Internationalcooperation.csproj
dotnet sln TotalAPI.sln add InternationalcooperationAPI/InternationalcooperationAPI.csproj
dotnet sln TotalAPI.sln add Investigations/Investigations.csproj
dotnet sln TotalAPI.sln add InvestigationsAPI/InvestigationsAPI.csproj
dotnet sln TotalAPI.sln add Laboratoryequipment/Laboratoryequipment.csproj
dotnet sln TotalAPI.sln add LaboratoryequipmentAPI/LaboratoryequipmentAPI.csproj
dotnet sln TotalAPI.sln add Land/Land.csproj
dotnet sln TotalAPI.sln add LandAPI/LandAPI.csproj
dotnet sln TotalAPI.sln add LandBranch/LandBranch.csproj
dotnet sln TotalAPI.sln add LandBranchAPI/LandBranchAPI.csproj
dotnet sln TotalAPI.sln add Library/Library.csproj
dotnet sln TotalAPI.sln add LibraryAPI/LibraryAPI.csproj
dotnet sln TotalAPI.sln add Maintenanceofeducationalbuilding/Maintenanceofeducationalbuilding.csproj
dotnet sln TotalAPI.sln add MaintenanceofeducationalbuildingAPI/MaintenanceofeducationalbuildingAPI.csproj
dotnet sln TotalAPI.sln add Maintenanceofmachineryandequipment/Maintenanceofmachineryandequipment.csproj
dotnet sln TotalAPI.sln add MaintenanceofmachineryandequipmentAPI/MaintenanceofmachineryandequipmentAPI.csproj
dotnet sln TotalAPI.sln add Ministryofsolidarity/Ministryofsolidarity.csproj
dotnet sln TotalAPI.sln add MinistryofsolidarityAPI/MinistryofsolidarityAPI.csproj
dotnet sln TotalAPI.sln add OfficeoftheDirectoroftheCommission/OfficeoftheDirectoroftheCommission.csproj
dotnet sln TotalAPI.sln add OfficeoftheDirectoroftheCommissionAPI/OfficeoftheDirectoroftheCommissionAPI.csproj
dotnet sln TotalAPI.sln add Organizationandmanagementhousing/Organizationandmanagementhousing.csproj
dotnet sln TotalAPI.sln add OrganizationandmanagementhousingAPI/OrganizationandmanagementhousingAPI.csproj
dotnet sln TotalAPI.sln add Organizationandmanagementtraining/Organizationandmanagementtraining.csproj
dotnet sln TotalAPI.sln add OrganizationandmanagementtrainingAPI/OrganizationandmanagementtrainingAPI.csproj
dotnet sln TotalAPI.sln add Pharmacy/Pharmacy.csproj
dotnet sln TotalAPI.sln add PharmacyAPI/PharmacyAPI.csproj
dotnet sln TotalAPI.sln add PlanningandFollowup/PlanningandFollowup.csproj
dotnet sln TotalAPI.sln add PlanningandFollowupAPI/PlanningandFollowupAPI.csproj
dotnet sln TotalAPI.sln add PooledDecimal/PooledDecimal.csproj
dotnet sln TotalAPI.sln add PooledDecimalAPI/PooledDecimalAPI.csproj
dotnet sln TotalAPI.sln add Postoffices/Postoffices.csproj
dotnet sln TotalAPI.sln add PostofficesAPI/PostofficesAPI.csproj
dotnet sln TotalAPI.sln add Probes/Probes.csproj
dotnet sln TotalAPI.sln add ProbesAPI/ProbesAPI.csproj
dotnet sln TotalAPI.sln add Publicrelations/Publicrelations.csproj
dotnet sln TotalAPI.sln add PublicrelationsAPI/PublicrelationsAPI.csproj
dotnet sln TotalAPI.sln add Purchase/Purchase.csproj
dotnet sln TotalAPI.sln add PurchaseAPI/PurchaseAPI.csproj
dotnet sln TotalAPI.sln add QualityManagement/QualityManagement.csproj
dotnet sln TotalAPI.sln add QualityManagementAPI/QualityManagementAPI.csproj
dotnet sln TotalAPI.sln add RentedBuildings/RentedBuildings.csproj
dotnet sln TotalAPI.sln add RentedBuildingsAPI/RentedBuildingsAPI.csproj
dotnet sln TotalAPI.sln add ResearchandStudies/ResearchandStudies.csproj
dotnet sln TotalAPI.sln add ResearchandStudiesAPI/ResearchandStudiesAPI.csproj
dotnet sln TotalAPI.sln add SalaryCalculation/SalaryCalculation.csproj
dotnet sln TotalAPI.sln add SalaryCalculationAPI/SalaryCalculationAPI.csproj
dotnet sln TotalAPI.sln add SchoolbranchesMap/SchoolbranchesMap.csproj
dotnet sln TotalAPI.sln add SchoolbranchesMapAPI/SchoolbranchesMapAPI.csproj
dotnet sln TotalAPI.sln add SchoolMap/SchoolMap.csproj
dotnet sln TotalAPI.sln add SchoolMapAPI/SchoolMapAPI.csproj
dotnet sln TotalAPI.sln add ServicesAssociation/ServicesAssociation.csproj
dotnet sln TotalAPI.sln add ServicesAssociationAPI/ServicesAssociationAPI.csproj
dotnet sln TotalAPI.sln add SocialSecurity/SocialSecurity.csproj
dotnet sln TotalAPI.sln add SocialSecurityAPI/SocialSecurityAPI.csproj
dotnet sln TotalAPI.sln add SocialSolidarityFund/SocialSolidarityFund.csproj
dotnet sln TotalAPI.sln add SocialSolidarityFundA/SocialSolidarityFundA.csproj
dotnet sln TotalAPI.sln add SocialSolidarityFundAAPI/SocialSolidarityFundAAPI.csproj
dotnet sln TotalAPI.sln add SocialSolidarityFundAPI/SocialSolidarityFundAPI.csproj
dotnet sln TotalAPI.sln add SocialSolidarityFundB/SocialSolidarityFundB.csproj
dotnet sln TotalAPI.sln add SocialSolidarityFundBAPI/SocialSolidarityFundBAPI.csproj
dotnet sln TotalAPI.sln add SocialSolidarityFundG/SocialSolidarityFundG.csproj
dotnet sln TotalAPI.sln add SocialSolidarityFundGAPI/SocialSolidarityFundGAPI.csproj
dotnet sln TotalAPI.sln add Store/Store.csproj
dotnet sln TotalAPI.sln add StoreAPI/StoreAPI.csproj
dotnet sln TotalAPI.sln add Timecontrol/Timecontrol.csproj
dotnet sln TotalAPI.sln add TimecontrolAPI/TimecontrolAPI.csproj
dotnet sln TotalAPI.sln add TimeManagement/TimeManagement.csproj
dotnet sln TotalAPI.sln add TimeManagementAPI/TimeManagementAPI.csproj
dotnet sln TotalAPI.sln add TimingAndPricing/TimingAndPricing.csproj
dotnet sln TotalAPI.sln add TimingAndPricingAPI/TimingAndPricingAPI.csproj
dotnet sln TotalAPI.sln add TransportandMovement/TransportandMovement.csproj
dotnet sln TotalAPI.sln add TransportandMovementAPI/TransportandMovementAPI.csproj
dotnet sln TotalAPI.sln add Typicalprocessing/Typicalprocessing.csproj
dotnet sln TotalAPI.sln add TypicalprocessingAPI/TypicalprocessingAPI.csproj
dotnet sln TotalAPI.sln add Vacation/Vacation.csproj
dotnet sln TotalAPI.sln add VacationAPI/VacationAPI.csproj
dotnet sln TotalAPI.sln add Weightsdifferences/Weightsdifferences.csproj
dotnet sln TotalAPI.sln add WeightsdifferencesAPI/WeightsdifferencesAPI.csproj
